const DONE_SEARCHING = 'Done Searching';
const NPM = 'npm';
const YARN = 'yarn';
const INSTALLER = Object.freeze({
  [NPM]: NPM,
  [YARN]: YARN,
});

const NPM_DEPENDENCY_INSTALL_OPTION = 'dependencies';
const NPM_DEV_DEPENDENCY_INSTALL_OPTION = 'devDependencies';
const NPM_OPTIONAL_DEPENDENCY_INSTALL_OPTION = 'optionalDependencies';
const NPM_GLOBAL_INSTALL_OPTION = 'global';

const NPM_INSTALL_OPTIONS = Object.freeze([
  NPM_DEPENDENCY_INSTALL_OPTION,
  NPM_DEV_DEPENDENCY_INSTALL_OPTION,
  NPM_OPTIONAL_DEPENDENCY_INSTALL_OPTION,
  NPM_GLOBAL_INSTALL_OPTION,
]);

const DEFAULT_INSTALLER_SAVE_OPTION = 'Default behavior';
const NPM_NO_SAVE_OPTION = 'Do not save';
const NPM_SAVE_EXACT_OPTION = 'Save exact version';
const NPM_DRY_RUN_OPTION = 'Dry run';

const NPM_SAVE_OPTIONS = Object.freeze([
  DEFAULT_INSTALLER_SAVE_OPTION,
  NPM_SAVE_EXACT_OPTION,
  NPM_NO_SAVE_OPTION,
  NPM_DRY_RUN_OPTION,
]);

const YARN_DEPENDENCY_ADD_OPTION = 'dependencies';
const YARN_DEV_DEPENDENCY_ADD_OPTION = 'devDependencies';
const YARN_PEER_DEPENDENCY_ADD_OPTION = 'peerDependencies';
const YARN_OPTIONAL_DEPENDENCY_ADD_OPTION = 'optionalDependencies';

const YARN_ADD_OPTIONS = Object.freeze([
  YARN_DEPENDENCY_ADD_OPTION,
  YARN_DEV_DEPENDENCY_ADD_OPTION,
  YARN_PEER_DEPENDENCY_ADD_OPTION,
  YARN_OPTIONAL_DEPENDENCY_ADD_OPTION,
]);

const YARN_SAVE_EXACT_VERSION = 'Save exact version';
const YARN_SAVE_MOST_RECENT_MINOR_VERSION = 'Save most recent minor version';

const YARN_SAVE_OPTIONS = Object.freeze([
  DEFAULT_INSTALLER_SAVE_OPTION,
  YARN_SAVE_EXACT_VERSION,
  YARN_SAVE_MOST_RECENT_MINOR_VERSION,
]);

export {
  DONE_SEARCHING,
  NPM,
  YARN,
  INSTALLER,
  NPM_DEPENDENCY_INSTALL_OPTION,
  NPM_DEV_DEPENDENCY_INSTALL_OPTION,
  NPM_OPTIONAL_DEPENDENCY_INSTALL_OPTION,
  NPM_GLOBAL_INSTALL_OPTION,
  NPM_INSTALL_OPTIONS,
  NPM_NO_SAVE_OPTION,
  NPM_SAVE_EXACT_OPTION,
  NPM_DRY_RUN_OPTION,
  NPM_SAVE_OPTIONS,
  YARN_DEPENDENCY_ADD_OPTION,
  YARN_DEV_DEPENDENCY_ADD_OPTION,
  YARN_PEER_DEPENDENCY_ADD_OPTION,
  YARN_OPTIONAL_DEPENDENCY_ADD_OPTION,
  YARN_ADD_OPTIONS,
  YARN_SAVE_EXACT_VERSION,
  YARN_SAVE_MOST_RECENT_MINOR_VERSION,
  YARN_SAVE_OPTIONS,
  DEFAULT_INSTALLER_SAVE_OPTION,
};
